# Generated by Django 4.2 on 2023-09-15 13:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='thought_distortions',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
