# Generated by Django 4.2 on 2023-09-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_count_journalentry_thought_distortions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='thought_distortions',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
