# Generated by Django 4.2 on 2023-09-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalentry_thought_distortion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='ThoughtDistortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=30)),
                ('confidence', models.FloatField()),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.journalentry')),
            ],
        ),
    ]
